### ISSUE TITLE
Chapters - Task list

### ISSUE THREAD

**Issue by Br0uge** [alrydia/Alrydia#1]
- [ ] Uvod
- [ ] Početak
- [ ] Glavni
- [ ] problem
- [ ] Događaji koji su usljedili
- [ ] Kakav je sada svijet
- [ ] Definiranje priče igre na koju će se graditi ostatak

**Comment by Br0uge** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Lore Summary](https://trello.com/c/jH5wJ9d0/1-lore-summary)
